from ArbolBinBusq import arbolBinBusq

if __name__ == '__main__':
    a=arbolBinBusq()
    a.insertar(10)
    a.insertar(5)
    a.insertar(15)
    a.insertar(3)
    a.insertar(7)
    a.insertar(12)
    a.insertar(17)
    a.insertar(1)
    a.insertar(4)
    a.insertar(6)
    a.insertar(8)
    a.insertar(11)
    a.insertar(13)
    a.insertar(16)
    a.insertar(18)
    a.insertar(13)
    a.inorden(a.getRaiz())
    print()
    a.preorden(a.getRaiz())
    print()
    a.postorden(a.getRaiz())
    print()
    print(a.busqueda(7).getObjeto())
    print(a.busqueda(9))
    print(a.busqueda(13).getCant())

